[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]


[tool.black]
line-length = 120
target-version = ['py38']
exclude = 'A new service for doing things./migrations'

[tool.isort]
profile = "black"
