"""
Install postgres extensions.

Revision ID: 1f3ddc3890e6
Revises: 4db156449750
Create Date: 2017-11-05 21:11:10.198222
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f3ddc3890e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """ Applies the migration. """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS extensions;')
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA extensions;')
    # ### end Alembic commands ###


def downgrade():
    """ Rolls back the migration. """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP SCHEMA extensions CASCADE;')
    # ### end Alembic commands ###
